In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [4]:
df=pd.read_csv("adult_with_headers.csv")
df.head()

age          workclass  fnlwgt   education  education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital_status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital_gain  capital_loss  hours_per_week  native_country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [5]:
df1=df.copy()

In [6]:
labelencoder = LabelEncoder()
df1['workclass'] = labelencoder.fit_transform(df1['workclass'])
df1

age  workclass  fnlwgt    education  education_num  \
0       39          7   77516    Bachelors             13   
1       50          6   83311    Bachelors             13   
2       38          4  215646      HS-grad              9   
3       53          4  234721         11th              7   
4       28          4  338409    Bachelors             13   
...    ...        ...     ...          ...            ...   
32556   27          4  257302   Assoc-acdm             12   
32557   40          4  154374      HS-grad              9   
32558   58          4  151910      HS-grad              9   
32559   22          4  201490      HS-grad              9   
32560   52          5  287927      HS-grad              9   

            marital_status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital_gain  capital_loss  hours_per_week  native_country  \
0         Male          2174             0              40   United-States   
1         Male             0             0              13   United-States   
2         Male             0             0              40   United-States   
3         Male             0             0              40   United-States   
4       Female             0             0              40            Cuba   
...        ...           ...           ...             ...             ...   
32556   Female             0             0              38   United-States   
32557     Male             0             0              40   United-States   
32558   Female             0             0              40   United-States   
32559     Male             0             0              20   United-States   
32560   Female         15024             0              40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [10]:
df2=df.copy()
df2.head()


age          workclass  fnlwgt   education  education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital_status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital_gain  capital_loss  hours_per_week  native_country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [11]:
enc=OneHotEncoder(handle_unknown='ignore')

In [19]:
enc.fit_transform(df2[['sex']]).toarray().astype('int')

array([[0, 1],
       [0, 1],
       [0, 1],
       ...,
       [1, 0],
       [0, 1],
       [1, 0]])

In [20]:
enc_df=pd.DataFrame(enc.fit_transform(df2[['sex']]).toarray().astype('int'),columns=['Male','Female'])
enc_df

Male  Female
0         0       1
1         0       1
2         0       1
3         0       1
4         1       0
...     ...     ...
32556     1       0
32557     0       1
32558     1       0
32559     0       1
32560     1       0

[32561 rows x 2 columns]

In [23]:
df_=df2.drop('sex',axis=1)
final_data=df_.join(enc_df)
final_data.head()

age          workclass  fnlwgt   education  education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital_status          occupation    relationship    race  \
0        Never-married        Adm-clerical   Not-in-family   White   
1   Married-civ-spouse     Exec-managerial         Husband   White   
2             Divorced   Handlers-cleaners   Not-in-family   White   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black   
4   Married-civ-spouse      Prof-specialty            Wife   Black   

   capital_gain  capital_loss  hours_per_week  native_country  income  Male  \
0          2174             0              40   United-States   <=50K     0   
1             0             0              13   United-States   <=50K     0   
2             0             0              40   United-States   <=50K     0   
3             0             0              40   United-States   <=50K     0   
4             0             0              40            Cuba   <=50K     1   

   Female  
0       1  
1       1  
2       1  
3       1  
4       0

In [28]:
data=pd.read_csv("adult_with_headers.csv")
data.head()

age          workclass  fnlwgt   education  education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital_status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital_gain  capital_loss  hours_per_week  native_country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [37]:
data=pd.get_dummies(data).astype('int')
data

age  fnlwgt  education_num  capital_gain  capital_loss  hours_per_week  \
0       39   77516             13          2174             0              40   
1       50   83311             13             0             0              13   
2       38  215646              9             0             0              40   
3       53  234721              7             0             0              40   
4       28  338409             13             0             0              40   
...    ...     ...            ...           ...           ...             ...   
32556   27  257302             12             0             0              38   
32557   40  154374              9             0             0              40   
32558   58  151910              9             0             0              40   
32559   22  201490              9             0             0              20   
32560   52  287927              9         15024             0              40   

       workclass_ ?  workclass_ Federal-gov  workclass_ Local-gov  \
0                 0                       0                     0   
1                 0                       0                     0   
2                 0                       0                     0   
3                 0                       0                     0   
4                 0                       0                     0   
...             ...                     ...                   ...   
32556             0                       0                     0   
32557             0                       0                     0   
32558             0                       0                     0   
32559             0                       0                     0   
32560             0                       0                     0   

       workclass_ Never-worked  ...  native_country_ Scotland  \
0                            0  ...                         0   
1                            0  ...                         0   
2                            0  ...                         0   
3                            0  ...                         0   
4                            0  ...                         0   
...                        ...  ...                       ...   
32556                        0  ...                         0   
32557                        0  ...                         0   
32558                        0  ...                         0   
32559                        0  ...                         0   
32560                        0  ...                         0   

       native_country_ South  native_country_ Taiwan  \
0                          0                       0   
1                          0                       0   
2                          0                       0   
3                          0                       0   
4                          0                       0   
...                      ...                     ...   
32556                      0                       0   
32557                      0                       0   
32558                      0                       0   
32559                      0                       0   
32560                      0                       0   

       native_country_ Thailand  native_country_ Trinadad&Tobago  \
0                             0                                0   
1                             0                                0   
2                             0                                0   
3                             0                                0   
4                             0                                0   
...                         ...                              ...   
32556                         0                                0   
32557                         0                                0   
32558                         0                                0   
32559                         0                                0   
325

In [24]:
#standard scaling
from sklearn.preprocessing import StandardScaler

In [39]:
scaler1=StandardScaler()
scaled_data=scaler1.fit_transform(data)
scaled_data

array([[ 0.03067056, -1.06361075,  1.13473876, ..., -0.02217266,
         0.56319851, -0.56319851],
       [ 0.83710898, -1.008707  ,  1.13473876, ..., -0.02217266,
         0.56319851, -0.56319851],
       [-0.04264203,  0.2450785 , -0.42005962, ..., -0.02217266,
         0.56319851, -0.56319851],
       ...,
       [ 1.42360965, -0.35877741, -0.42005962, ..., -0.02217266,
         0.56319851, -0.56319851],
       [-1.21564337,  0.11095988, -0.42005962, ..., -0.02217266,
         0.56319851, -0.56319851],
       [ 0.98373415,  0.92989258, -0.42005962, ..., -0.02217266,
        -1.77557289,  1.77557289]])

In [40]:
#min_max scaling
from sklearn.preprocessing import MinMaxScaler

In [41]:
scaler2=MinMaxScaler()
scaled_data1=scaler2.fit_transform(data)
scaled_data1

array([[0.30136986, 0.0443019 , 0.8       , ..., 0.        , 1.        ,
        0.        ],
       [0.45205479, 0.0482376 , 0.8       , ..., 0.        , 1.        ,
        0.        ],
       [0.28767123, 0.13811345, 0.53333333, ..., 0.        , 1.        ,
        0.        ],
       ...,
       [0.56164384, 0.09482688, 0.53333333, ..., 0.        , 1.        ,
        0.        ],
       [0.06849315, 0.12849934, 0.53333333, ..., 0.        , 1.        ,
        0.        ],
       [0.47945205, 0.18720338, 0.53333333, ..., 0.        , 0.        ,
        1.        ]])

In [53]:
#isolation forest
from sklearn.ensemble import IsolationForest

In [54]:
clf=IsolationForest(random_state=10,contamination=.01)
clf.fit(data)

IsolationForest(contamination=0.01, random_state=10)

In [55]:
y_pred_outliers=clf.predict(data)
y_pred_outliers

array([1, 1, 1, ..., 1, 1, 1])

In [57]:
data['score']=clf.decision_function(data)
data['anomaly']=clf.predict(data)


In [58]:
data[data['anomaly']==-1].index.values   #outlier data points

array([    6,    61,    93,   157,   297,   312,   404,   554,   668,
         873,   916,  1029,  1034,  1036,  1092,  1115,  1281,  1291,
        1327,  1387,  1391,  1458,  1562,  1570,  1865,  1971,  2003,
        2107,  2130,  2259,  2330,  2469,  2775,  2784,  2906,  2961,
        3021,  3211,  3343,  3612,  3879,  3909,  4018,  4066,  4155,
        4169,  4281,  4337,  4381,  4409,  4545,  4598,  4625,  4639,
        4656,  4704,  4718,  4768,  5012,  5027,  5127,  5196,  5219,
        5227,  5423,  5435,  5530,  5592,  5720,  5774,  5870,  5979,
        6120,  6125,  6131,  6150,  6225,  6295,  6359,  6493,  6524,
        6590,  6595,  6621,  6751,  6952,  6991,  7047,  7059,  7202,
        7234,  7258,  7275,  7285,  7404,  7461,  7606,  7756,  7829,
        7894,  7905,  8036,  8251,  8282,  8478,  8508,  8535,  8603,
        8610,  8649,  8699,  8947,  9106,  9147,  9248,  9559,  9568,
        9580,  9588,  9599,  9626,  9735,  9860,  9952,  9972, 10041,
       10343, 10458,