# chi-square test

In [2]:
satisfaction=['very satisfied','satisfied','neutral','unsatisfied','very unsatisfied']
smart_thermostat=[50,80,60,30,20]
smart_light=[70,100,90,50,50]
total=[120,180,150,80,70]

In [3]:
import pandas as pd
data=pd.DataFrame({'satisfaction':satisfaction,
                   'smart_thermostat':smart_thermostat,
                   'smart_light':smart_light,
                   'total':total})

In [4]:
data

satisfaction  smart_thermostat  smart_light  total
0    very satisfied                50           70    120
1         satisfied                80          100    180
2           neutral                60           90    150
3       unsatisfied                30           50     80
4  very unsatisfied                20           50     70

In [7]:
crosstable =pd.crosstab(data['smart_thermostat'],data['smart_light'])
crosstable

smart_light       50   70   90   100
smart_thermostat                    
20                  1    0    0    0
30                  1    0    0    0
50                  0    1    0    0
60                  0    0    1    0
80                  0    0    0    1

In [10]:
#chi_square test
from scipy.stats import chi2_contingency
chi,p,dof,exp_freq = chi2_contingency(crosstable)
print(chi,p,exp_freq)

15.000000000000002 0.24143645097027544 [[0.4 0.2 0.2 0.2]
 [0.4 0.2 0.2 0.2]
 [0.4 0.2 0.2 0.2]
 [0.4 0.2 0.2 0.2]
 [0.4 0.2 0.2 0.2]]


In [12]:
#hypothesis decision
if p<0.05:
    print('Reject H0: there is a significant association')
else:
    print('Accept H0: no significant association')     

Accept H0: no significant association


# hypotheses test

In [1]:
# given data
s_mean=3050
mu=600
cost_model=1000+(5*600)
sigma=5*25
n=25 #sample size
alpha=0.05

In [2]:
#H0: mu = cost_model
#H1: mu =! cost_model

In [4]:
#calculate the test statistic
import numpy as np
z = (s_mean - cost_model)/(sigma/np.sqrt(n))
z

-38.0

In [5]:
# critical value (z)
from scipy.stats import norm
z_crit = norm.ppf(1-alpha/2)
z_crit

1.959963984540054

In [9]:
# decision
if abs(z)>z_crit:
    decision = 'reject the null hypotesis'

else:
    decision ='accept the null hypotesis'

decision

'reject the null hypotesis'